In [2]:
import pandas as pd
import os

In [3]:
files = [
    'ACP-Households-by-County-January-December-2022.xlsx',
    'ACP-Households-by-County-January-July-2023.xlsx'
]

In [6]:
# df = pd.DataFrame()

# for file in files:
#     print(file)
df = pd.concat(pd.read_excel(os.path.join('data', file)) for file in files)

In [7]:
df

,Data Month,State,State Name,County Name,State FIPS,County FIPS,Net New Enrollments Alternative Verification Process,Net New Enrollments Verified by School,Net New Enrollments Lifeline,Net New Enrollments National Verifier Application,Net New Enrollments total,Total Alternative Verification Process,Total Verified by School,Total Lifeline,Total National Verifier Application,Total Subscribers
0,2022-01-01,AL,ALABAMA,AUTAUGA COUNTY,1,001,46.0,-1.0,20.0,53.0,118.0,618.0,2.0,440.0,874.0,1934.0
1,2022-01-01,AL,ALABAMA,BALDWIN COUNTY,1,003,-13.0,0.0,78.0,114.0,179.0,521.0,5.0,959.0,1281.0,2766.0
2,2022-01-01,AL,ALABAMA,BARBOUR COUNTY,1,005,41.0,0.0,56.0,25.0,122.0,881.0,1.0,444.0,417.0,1743.0
3,2022-01-01,AL,ALABAMA,BIBB COUNTY,1,007,0.0,0.0,14.0,23.0,37.0,9.0,5.0,182.0,304.0,500.0
4,2022-01-01,AL,ALABAMA,BLOUNT COUNTY,1,009,12.0,-1.0,18.0,46.0,75.0,196.0,11.0,293.0,573.0,1073.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22954,2023-07-01,PR,PUERTO RICO,**NOT AVAILABLE**,72,**NOT AVAILABLE**,0.0,0.0,122.0,13.0,135.0,0.0,0.0,176.0,168.0,344.0
22955,2023-07-01,VI,VIRGIN ISLANDS,ST. CROIX ISLAND,78,010,0.0,0.0,-3.0,178.0,175.0,0.0,0.0,87.0,2547.0,2634.0
22956,2023-07-01,VI,VIRGIN ISLANDS,ST. JOHN ISLAND,78,020,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,47.0,47.0
22957,2023-07-01,VI,VIRGIN ISLANDS,ST. THOMAS ISLAND,78,030,0.0,0.0,5.0,57.0,62.0,0.0,0.0,73.0,1666.0,1739.0
22958,2023-07-01,VI,VIRGIN ISLANDS,**NOT AVAILABLE**,78,**NOT AVAILABLE**,0.0,0.0,0.0,-21.0,-21.0,0.0,0.0,0.0,0.0,0.0

In [14]:
df['Data Month'].value_counts().sort_index()

Data Month
2022-01-01    3263
2022-02-01    3265
2022-03-01    3266
2022-04-01    3267
2022-05-01    3267
2022-06-01    3270
2022-07-01    3280
2022-08-01    3280
2022-09-01    3279
2022-10-01    3280
2022-11-01    3280
2022-12-01    3279
2023-01-01    3278
2023-02-01    3278
2023-03-01    3278
2023-04-01    3280
2023-05-01    3282
2023-06-01    3282
2023-07-01    3281
Name: count, dtype: int64

In [19]:
df = df.query("State == 'WA'").reset_index(drop=True)

In [23]:
df.to_parquet(os.path.join('data', 'waAcp.parquet'))